updated the configs
sourcefuse/terraform-aws-refarch-tags pull request #12
Opened 2023-02-28 11:41 UTC by mayank0202

2023-02-28 15:34 UTC, tsaucier-sf commented
The `.version` file needs to be incremented. Run `pre-commit run -a` from the root and resolve any errors please.

2023-02-28 15:35 UTC, tsaucier-sf requested changes
See comment about pre-commit and .version

2023-02-28 16:28 UTC, mayank0202 commented
> The `.version` file needs to be incremented. Run `pre-commit run -a` from the root and resolve any errors please.

Sure

2023-02-28 21:39 UTC, tsaucier-sf approved these changes

2023-03-02 15:13 UTC, jamescrowley321 approved these changes

2023-03-02 15:13 UTC, merged